server:
  port: 8082

spring:
  application:
    name: ingestion-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/trafficlens}
    username: ${SPRING_DATASOURCE_USERNAME:trafficlens}
    password: ${SPRING_DATASOURCE_PASSWORD:trafficlens123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
